# Generated by Django 5.2.8 on 2026-06-11 14:58

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(help_text='Upload the banner image', upload_to='advertisements/')),
                ('target_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g., IN, US', max_length=5, unique=True)),
                ('timezone_offset', models.CharField(default='UTC', help_text='e.g., Asia/Kolkata', max_length=50)),
                ('is_whitelisted', models.BooleanField(default=False, help_text='SuperAdmin must enable this for registration')),
            ],
            options={
                'verbose_name_plural': 'Master Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('context', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORG_ADMIN', 'Organization Admin'), ('PUBLIC_USER', 'Public User / Donor')], default='PUBLIC_USER', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('email_verification_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='api.mastercountry')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MasterDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.masterstate')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('A1+', 'A1 Positive'), ('A1-', 'A1 Negative'), ('A1B+', 'A1B Positive'), ('A1B-', 'A1B Negative'), ('A2+', 'A2 Positive'), ('A2-', 'A2 Negative'), ('A2B+', 'A2B Positive'), ('A2B-', 'A2B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('BBG', 'Bombay Blood Group'), ('INRA', 'INRA'), ('O+', 'O Positive'), ('O-', 'O Negative')], db_index=True, max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(validators=[api.models.validate_past_date])),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_permanently_deferred', models.BooleanField(default=False)),
                ('deferral_reason', models.TextField(blank=True, help_text='e.g., Medical condition, recent tattoo', null=True)),
                ('has_consented', models.BooleanField(default=False, help_text='Donor explicitly consented to data storage and contact.')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mastercountry')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.masterdistrict')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.masterstate')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Custom URL handle for the public profile.', max_length=150, null=True, unique=True)),
                ('org_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('BLOOD_BANK', 'Blood Bank'), ('NGO', 'NGO / Volunteer Group'), ('CLINIC', 'Private Clinic')], max_length=20)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('address_line', models.TextField()),
                ('logo', models.ImageField(blank=True, help_text='Square logo for dashboard & public profile', null=True, upload_to='organization/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='organization/banners/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending SuperAdmin Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('is_paid', models.BooleanField(default=False, help_text='True if the organization has an active paid subscription.')),
                ('is_searchable', models.BooleanField(db_index=True, default=True, help_text="If False, this organization's donors are hidden from public search.")),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mastercountry')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.masterdistrict')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.masterstate')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDonor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('A1+', 'A1 Positive'), ('A1-', 'A1 Negative'), ('A1B+', 'A1B Positive'), ('A1B-', 'A1B Negative'), ('A2+', 'A2 Positive'), ('A2-', 'A2 Negative'), ('A2B+', 'A2B Positive'), ('A2B-', 'A2B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('BBG', 'Bombay Blood Group'), ('INRA', 'INRA'), ('O+', 'O Positive'), ('O-', 'O Negative')], db_index=True, max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(validators=[api.models.validate_past_date])),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_permanently_deferred', models.BooleanField(default=False)),
                ('deferral_reason', models.TextField(blank=True, help_text='e.g., Medical condition, recent tattoo', null=True)),
                ('has_consented', models.BooleanField(default=False, help_text='Donor explicitly consented to data storage and contact.')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.mastercountry')),
                ('district', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.masterdistrict')),
                ('state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.masterstate')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.organization')),
            ],
            options={
                'verbose_name': 'historical donor',
                'verbose_name_plural': 'historical donors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDonationRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood (RBC)'), ('PLATELETS', 'Platelets (Apheresis)'), ('PLASMA', 'Plasma')], default='WHOLE_BLOOD', max_length=20)),
                ('donation_date', models.DateField(default=django.utils.timezone.now)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.donor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.organization')),
            ],
            options={
                'verbose_name': 'historical donation record',
                'verbose_name_plural': 'historical donation records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='donor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='api.organization'),
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood (RBC)'), ('PLATELETS', 'Platelets (Apheresis)'), ('PLASMA', 'Plasma')], default='WHOLE_BLOOD', max_length=20)),
                ('donation_date', models.DateField(default=django.utils.timezone.now)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to='api.donor')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization')),
            ],
            options={
                'ordering': ['-donation_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='api.organization'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('upi_reference', models.CharField(help_text='UTR / Reference Number from UPI App', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected / Invalid UTR')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.organization')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.tenantsupportticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'is_searchable'], name='api_organiz_status_becb19_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['is_deleted'], name='api_donor_is_dele_757264_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['organization', 'is_deleted'], name='api_donor_organiz_70d2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group', 'district', 'state'], name='api_donor_blood_g_5b92d2_idx'),
        ),
    ]
