# Generated by Django 5.2.8 on 2026-06-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Square logo for dashboard & public profile', null=True, upload_to='organization/logos/'),
        ),
    ]
