# Generated by Django 5.2.8 on 2026-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image to display in the Home Page Hero Slider', upload_to='hero_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Optional description for accessibility/SEO', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the slide order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='show_on_hero',
            field=models.BooleanField(default=False, help_text='Check to randomly include this ad as the last slide in the Home Page Hero section.'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='portrait_image',
            field=models.ImageField(blank=True, help_text='Portrait image for home pages', null=True, upload_to='advertisements/portraits/'),
        ),
    ]
