# Generated by Django 6.0.5 on 2026-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('A1+', 'A1 Positive'), ('A1-', 'A1 Negative'), ('A1B+', 'A1B Positive'), ('A1B-', 'A1B Negative'), ('A2+', 'A2 Positive'), ('A2-', 'A2 Negative'), ('A2B+', 'A2B Positive'), ('A2B-', 'A2B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('BBG', 'Bombay Blood Group'), ('INRA', 'INRA'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=5),
        ),
    ]
