# Generated by Django 5.2.8 on 2026-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_organization_plan_tier_organization_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
