# Generated by Django 5.2.8 on 2026-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_heroimage_advertisement_show_on_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Landscape hero image for homepage slide', null=True, upload_to='advertisements/hero/'),
        ),
    ]
