# Generated by Django 5.2.8 on 2026-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_email_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_searchable',
            field=models.BooleanField(default=True, help_text="If False, this organization's donors are hidden from public search."),
        ),
    ]
