# Generated by Django 5.2.8 on 2026-06-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_advertisement_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_map_link',
            field=models.TextField(blank=True, help_text='Google Maps Embed URL or iframe code', null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='organization',
            field=models.ForeignKey(help_text='Protected to prevent accidental hard-deletion of medical records if an Org is deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='donors', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='historicaldonor',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Protected to prevent accidental hard-deletion of medical records if an Org is deleted.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.organization'),
        ),
    ]
