# Generated by Django 5.2.8 on 2026-05-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organization_is_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='organization/banners/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='gallery_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='organization/gallery/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='gallery_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='organization/gallery/'),
        ),
    ]
