# Generated by Django 5.2.8 on 2026-05-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organization_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, help_text='Custom URL handle for the public profile.', max_length=150, null=True, unique=True),
        ),
    ]
