# Generated by Django 6.0.5 on 2026-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_donor_deleted_at_donor_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='has_consented',
            field=models.BooleanField(default=False, help_text='Donor explicitly consented to data storage and contact.'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('A1+', 'A1 Positive'), ('A1-', 'A1 Negative'), ('A1B+', 'A1B Positive'), ('A1B-', 'A1B Negative'), ('A2+', 'A2 Positive'), ('A2-', 'A2 Negative'), ('A2B+', 'A2B Positive'), ('A2B-', 'A2B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('BBG', 'Bombay Blood Group'), ('INRA', 'INRA'), ('O+', 'O Positive'), ('O-', 'O Negative')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending SuperAdmin Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
