# Generated by Django 5.2.8 on 2026-05-24 04:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(validators=[api.models.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True, validators=[api.models.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_searchable',
            field=models.BooleanField(db_index=True, default=True, help_text="If False, this organization's donors are hidden from public search."),
        ),
    ]
