# Generated by Django 5.2.8 on 2026-05-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_donor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercountry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Master Countries'},
        ),
        migrations.AlterModelOptions(
            name='masterdistrict',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='masterstate',
            options={'ordering': ['name']},
        ),
    ]
