# Generated by Django 5.2.8 on 2026-05-29 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_mastercountry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='last_donation_date',
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood (RBC)'), ('PLATELETS', 'Platelets (Apheresis)'), ('PLASMA', 'Plasma')], default='WHOLE_BLOOD', max_length=20)),
                ('donation_date', models.DateField(default=django.utils.timezone.now)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to='api.donor')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization')),
            ],
            options={
                'ordering': ['-donation_date', '-created_at'],
            },
        ),
    ]
