from django.core.management.base import BaseCommand
from django.db import transaction
from api.models import MasterCountry, MasterState, MasterDistrict

class Command(BaseCommand):
    help = 'Populates or updates the database with comprehensive Country, State, and District data for India, UAE, and Saudi Arabia'

    @transaction.atomic
    def handle(self, *args, **kwargs):
        geo_data = {
            'India': {
                'code': 'IN',
                'timezone_offset': 'Asia/Kolkata',
                'is_whitelisted': True,
                'states': {
                    'Andhra Pradesh': [
                        'Anantapur',
                        'Chittoor',
                        'East Godavari',
                        'Guntur',
                        'Krishna',
                        'Kurnool',
                        'Nellore',
                        'Prakasam',
                        'Srikakulam',
                        'Visakhapatnam',
                        'Vizianagaram',
                        'West Godavari',
                        'YSR Kadapa'
                    ],
                    'Arunachal Pradesh': [
                        'Tawang',
                        'West Kameng',
                        'East Kameng',
                        'Papum Pare',
                        'Kurung Kumey',
                        'Kra Daadi',
                        'Lower Subansiri',
                        'Upper Subansiri',
                        'West Siang',
                        'East Siang'
                    ],
                    'Assam': [
                        'Baksa',
                        'Barpeta',
                        'Biswanath',
                        'Bongaigaon',
                        'Cachar',
                        'Charaideo',
                        'Chirang',
                        'Darrang',
                        'Dhemaji',
                        'Dhubri',
                        'Dibrugarh',
                        'Goalpara',
                        'Golaghat',
                        'Hailakandi',
                        'Jorhat',
                        'Kamrup',
                        'Kamrup Metropolitan',
                        'Karbi Anglong',
                        'Karimganj',
                        'Lakhimpur',
                        'Majuli',
                        'Morigaon',
                        'Nagaon',
                        'Nalbari',
                        'Sivasagar',
                        'Sonitpur',
                        'South Salmara-Mankachar',
                        'Tinsukia',
                        'Udalguri',
                        'West Karbi Anglong'
                    ],
                    'Bihar': [
                        'Araria',
                        'Arwal',
                        'Aurangabad',
                        'Banka',
                        'Begusarai',
                        'Bhagalpur',
                        'Bhojpur',
                        'Buxar',
                        'Darbhanga',
                        'East Champaran',
                        'Gaya',
                        'Gopalganj',
                        'Jamui',
                        'Jehanabad',
                        'Kaimur',
                        'Katihar',
                        'Khagaria',
                        'Kishanganj',
                        'Lakhisarai',
                        'Madhepura',
                        'Madhubani',
                        'Munger',
                        'Muzaffarpur',
                        'Nalanda',
                        'Nawada',
                        'Patna',
                        'Purnia',
                        'Rohtas',
                        'Saharsa',
                        'Samastipur',
                        'Saran',
                        'Sheikhpura',
                        'Sheohar',
                        'Sitamarhi',
                        'Siwan',
                        'Supaul',
                        'Vaishali',
                        'West Champaran'
                    ],
                    'Chhattisgarh': [
                        'Balod',
                        'Baloda Bazar',
                        'Balrampur',
                        'Bastar',
                        'Bemetara',
                        'Bijapur',
                        'Bilaspur',
                        'Dantewada',
                        'Dhamtari',
                        'Durg',
                        'Gariaband',
                        'Janjgir-Champa',
                        'Jashpur',
                        'Kabirdham',
                        'Kanker',
                        'Kondagaon',
                        'Korba',
                        'Koriya',
                        'Mahasamund',
                        'Mungeli',
                        'Narayanpur',
                        'Raigarh',
                        'Raipur',
                        'Rajnandgaon',
                        'Sukma',
                        'Surajpur',
                        'Surguja'
                    ],
                    'Goa': [
                        'North Goa',
                        'South Goa'
                    ],
                    'Gujarat': [
                        'Ahmedabad',
                        'Amreli',
                        'Anand',
                        'Aravalli',
                        'Banaskantha',
                        'Bharuch',
                        'Bhavnagar',
                        'Botad',
                        'Chhota Udaipur',
                        'Dahod',
                        'Dang',
                        'Devbhoomi Dwarka',
                        'Gandhinagar',
                        'Gir Somnath',
                        'Jamnagar',
                        'Junagadh',
                        'Kheda',
                        'Kutch',
                        'Mahisagar',
                        'Mehsana',
                        'Morbi',
                        'Narmada',
                        'Navsari',
                        'Panchmahal',
                        'Patan',
                        'Porbandar',
                        'Rajkot',
                        'Sabarkantha',
                        'Surat',
                        'Surendranagar',
                        'Tapi',
                        'Vadodara',
                        'Valsad'
                    ],
                    'Haryana': [
                        'Ambala',
                        'Bhiwani',
                        'Charkhi Dadri',
                        'Faridabad',
                        'Fatehabad',
                        'Gurugram',
                        'Hisar',
                        'Jhajjar',
                        'Jind',
                        'Kaithal',
                        'Karnal',
                        'Kurukshetra',
                        'Mahendragarh',
                        'Nuh',
                        'Palwal',
                        'Panchkula',
                        'Panipat',
                        'Rewari',
                        'Rohtak',
                        'Sirsa',
                        'Sonipat',
                        'Yamunanagar'
                    ],
                    'Himachal Pradesh': [
                        'Bilaspur',
                        'Chamba',
                        'Hamirpur',
                        'Kangra',
                        'Kinnaur',
                        'Kullu',
                        'Lahaul and Spiti',
                        'Mandi',
                        'Shimla',
                        'Sirmaur',
                        'Solan',
                        'Una'
                    ],
                    'Jharkhand': [
                        'Bokaro',
                        'Chatra',
                        'Deoghar',
                        'Dhanbad',
                        'Dumka',
                        'East Singhbhum',
                        'Garhwa',
                        'Giridih',
                        'Godda',
                        'Gumla',
                        'Hazaribagh',
                        'Jamtara',
                        'Khunti',
                        'Koderma',
                        'Latehar',
                        'Lohardaga',
                        'Pakur',
                        'Palamu',
                        'Ramgarh',
                        'Ranchi',
                        'Sahibganj',
                        'Seraikela Kharsawan',
                        'Simdega',
                        'West Singhbhum'
                    ],
                    'Karnataka': [
                        'Bagalkot',
                        'Ballari (Bellary)',
                        'Belagavi (Belgaum)',
                        'Bengaluru Rural',
                        'Bengaluru Urban',
                        'Bidar',
                        'Chamarajanagar',
                        'Chikballapur',
                        'Chikkamagaluru',
                        'Chitradurga',
                        'Dakshina Kannada',
                        'Davanagere',
                        'Dharwad',
                        'Gadag',
                        'Hassan',
                        'Haveri',
                        'Kalaburagi (Gulbarga)',
                        'Kodagu',
                        'Kolar',
                        'Koppal',
                        'Mandya',
                        'Mysuru (Mysore)',
                        'Raichur',
                        'Ramanagara',
                        'Shivamogga (Shimoga)',
                        'Tumakuru (Tumkur)',
                        'Udupi',
                        'Uttara Kannada',
                        'Vijayapura (Bijapur)',
                        'Yadgir'
                    ],
                    'Kerala': [
                        'Alappuzha',
                        'Ernakulam',
                        'Idukki',
                        'Kannur',
                        'Kasaragod',
                        'Kollam',
                        'Kottayam',
                        'Kozhikode',
                        'Malappuram',
                        'Palakkad',
                        'Pathanamthitta',
                        'Thiruvananthapuram',
                        'Thrissur',
                        'Wayanad'
                    ],
                    'Madhya Pradesh': [
                        'Bhopal',
                        'Indore',
                        'Jabalpur',
                        'Gwalior',
                        'Ujjain',
                        'Sagar',
                        'Dewas',
                        'Satna',
                        'Ratlam',
                        'Rewa',
                        'Murwara',
                        'Singrauli',
                        'Burhanpur',
                        'Khandwa',
                        'Morena',
                        'Bhind',
                        'Chhindwara',
                        'Guna',
                        'Shivpuri',
                        'Vidisha'
                    ],
                    'Maharashtra': [
                        'Ahmednagar',
                        'Akola',
                        'Amravati',
                        'Aurangabad',
                        'Beed',
                        'Bhandara',
                        'Buldhana',
                        'Chandrapur',
                        'Dhule',
                        'Gadchiroli',
                        'Gondia',
                        'Hingoli',
                        'Jalgaon',
                        'Jalna',
                        'Kolhapur',
                        'Latur',
                        'Mumbai City',
                        'Mumbai Suburban',
                        'Nagpur',
                        'Nanded',
                        'Nandurbar',
                        'Nashik',
                        'Osmanabad',
                        'Palghar',
                        'Parbhani',
                        'Pune',
                        'Raigad',
                        'Ratnagiri',
                        'Sangli',
                        'Satara',
                        'Sindhudurg',
                        'Solapur',
                        'Thane',
                        'Wardha',
                        'Washim',
                        'Yavatmal'
                    ],
                    'Manipur': [
                        'Bishnupur',
                        'Chandel',
                        'Churachandpur',
                        'Imphal East',
                        'Imphal West',
                        'Jiribam',
                        'Kakching',
                        'Kamjong',
                        'Kangpokpi',
                        'Noney',
                        'Pherzawl',
                        'Senapati',
                        'Tamenglong',
                        'Tengnoupal',
                        'Thoubal',
                        'Ukhrul'
                    ],
                    'Meghalaya': [
                        'East Garo Hills',
                        'East Jaintia Hills',
                        'East Khasi Hills',
                        'North Garo Hills',
                        'Ri Bhoi',
                        'South Garo Hills',
                        'South West Garo Hills',
                        'South West Khasi Hills',
                        'West Garo Hills',
                        'West Jaintia Hills',
                        'West Khasi Hills'
                    ],
                    'Mizoram': [
                        'Aizawl',
                        'Champhai',
                        'Kolasib',
                        'Lawngtlai',
                        'Lunglei',
                        'Mamit',
                        'Saiha',
                        'Serchhip'
                    ],
                    'Nagaland': [
                        'Dimapur',
                        'Kiphire',
                        'Kohima',
                        'Longleng',
                        'Mokokchung',
                        'Mon',
                        'Peren',
                        'Phek',
                        'Tuensang',
                        'Wokha',
                        'Zunheboto'
                    ],
                    'Odisha': [
                        'Angul',
                        'Balangir',
                        'Balasore',
                        'Bargarh',
                        'Bhadrak',
                        'Boudh',
                        'Cuttack',
                        'Deogarh',
                        'Dhenkanal',
                        'Gajapati',
                        'Ganjam',
                        'Jagatsinghapur',
                        'Jajpur',
                        'Jharsuguda',
                        'Kalahandi',
                        'Kandhamal',
                        'Kendrapara',
                        'Kendujhar',
                        'Khordha',
                        'Koraput',
                        'Malkangiri',
                        'Mayurbhanj',
                        'Nabarangpur',
                        'Nayagarh',
                        'Nuapada',
                        'Puri',
                        'Rayagada',
                        'Sambalpur',
                        'Subarnapur',
                        'Sundargarh'
                    ],
                    'Punjab': [
                        'Amritsar',
                        'Barnala',
                        'Bathinda',
                        'Faridkot',
                        'Fatehgarh Sahib',
                        'Fazilka',
                        'Ferozepur',
                        'Gurdaspur',
                        'Hoshiarpur',
                        'Jalandhar',
                        'Kapurthala',
                        'Ludhiana',
                        'Mansa',
                        'Moga',
                        'Muktsar',
                        'Nawanshahr',
                        'Pathankot',
                        'Patiala',
                        'Rupnagar',
                        'Sahibzada Ajit Singh Nagar (Mohali)',
                        'Sangrur',
                        'Tarn Taran'
                    ],
                    'Rajasthan': [
                        'Ajmer',
                        'Alwar',
                        'Banswara',
                        'Baran',
                        'Barmer',
                        'Bharatpur',
                        'Bhilwara',
                        'Bikaner',
                        'Bundi',
                        'Chittorgarh',
                        'Churu',
                        'Dausa',
                        'Dholpur',
                        'Dungarpur',
                        'Hanumangarh',
                        'Jaipur',
                        'Jaisalmer',
                        'Jalore',
                        'Jhalawar',
                        'Jhunjhunu',
                        'Jodhpur',
                        'Karauli',
                        'Kota',
                        'Nagaur',
                        'Pali',
                        'Pratapgarh',
                        'Rajsamand',
                        'Sawai Madhopur',
                        'Sikar',
                        'Sirohi',
                        'Sri Ganganagar',
                        'Tonk',
                        'Udaipur'
                    ],
                    'Sikkim': [
                        'East Sikkim',
                        'North Sikkim',
                        'South Sikkim',
                        'West Sikkim'
                    ],
                    'Tamil Nadu': [
                        'Chennai',
                        'Coimbatore',
                        'Cuddalore',
                        'Dharmapuri',
                        'Dindigul',
                        'Erode',
                        'Kanchipuram',
                        'Kanyakumari',
                        'Karur',
                        'Krishnagiri',
                        'Madurai',
                        'Nagapattinam',
                        'Namakkal',
                        'Nilgiris',
                        'Perambalur',
                        'Pudukkottai',
                        'Ramanathapuram',
                        'Salem',
                        'Sivaganga',
                        'Thanjavur',
                        'Theni',
                        'Thoothukudi',
                        'Tiruchirappalli',
                        'Tirunelveli',
                        'Tiruppur',
                        'Tiruvallur',
                        'Tiruvannamalai',
                        'Tiruvarur',
                        'Vellore',
                        'Viluppuram',
                        'Virudhunagar'
                    ],
                    'Telangana': [
                        'Adilabad',
                        'Bhadradri Kothagudem',
                        'Hyderabad',
                        'Jagtial',
                        'Jangaon',
                        'Jayashankar Bhupalpally',
                        'Jogulamba Gadwal',
                        'Kamareddy',
                        'Karimnagar',
                        'Khammam',
                        'Komaram Bheem Asifabad',
                        'Mahabubabad',
                        'Mahabubnagar',
                        'Mancherial',
                        'Medak',
                        'Medchal',
                        'Nagarkurnool',
                        'Nalgonda',
                        'Nirmal',
                        'Nizamabad',
                        'Peddapalli',
                        'Rajanna Sircilla',
                        'Ranga Reddy',
                        'Sangareddy',
                        'Siddipet',
                        'Suryapet',
                        'Vikarabad',
                        'Wanaparthy',
                        'Warangal (Rural)',
                        'Warangal (Urban)',
                        'Yadadri Bhuvanagiri'
                    ],
                    'Tripura': [
                        'Dhalai',
                        'Gomati',
                        'Khowai',
                        'North Tripura',
                        'Sepahijala',
                        'South Tripura',
                        'Unakoti',
                        'West Tripura'
                    ],
                    'Uttar Pradesh': [
                        'Agra',
                        'Aligarh',
                        'Prayagraj (Allahabad)',
                        'Ambedkar Nagar',
                        'Amethi',
                        'Amroha',
                        'Auraiya',
                        'Azamgarh',
                        'Baghpat',
                        'Bahraich',
                        'Ballia',
                        'Balrampur',
                        'Banda',
                        'Barabanki',
                        'Bareilly',
                        'Basti',
                        'Bhadohi',
                        'Bijnor',
                        'Budaun',
                        'Bulandshahr',
                        'Chandauli',
                        'Chitrakoot',
                        'Deoria',
                        'Etah',
                        'Etawah',
                        'Ayodhya (Faizabad)',
                        'Farrukhabad',
                        'Fatehpur',
                        'Firozabad',
                        'Gautam Buddha Nagar (Noida)',
                        'Ghaziabad',
                        'Ghazipur',
                        'Gonda',
                        'Gorakhpur',
                        'Hamirpur',
                        'Hapur',
                        'Hardoi',
                        'Hathras',
                        'Jalaun',
                        'Jaunpur',
                        'Jhansi',
                        'Kannauj',
                        'Kanpur Dehat',
                        'Kanpur Nagar',
                        'Kasganj',
                        'Kaushambi',
                        'Kushinagar',
                        'Lakhimpur Kheri',
                        'Lalitpur',
                        'Lucknow',
                        'Maharajganj',
                        'Mahoba',
                        'Mainpuri',
                        'Mathura',
                        'Mau',
                        'Meerut',
                        'Mirzapur',
                        'Moradabad',
                        'Muzaffarnagar',
                        'Pilibhit',
                        'Pratapgarh',
                        'Raebareli',
                        'Rampur',
                        'Saharanpur',
                        'Sambhal',
                        'Sant Kabir Nagar',
                        'Shahjahanpur',
                        'Shamli',
                        'Shravasti',
                        'Siddharthnagar',
                        'Sitapur',
                        'Sonbhadra',
                        'Sultanpur',
                        'Unnao',
                        'Varanasi'
                    ],
                    'Uttarakhand': [
                        'Almora',
                        'Bageshwar',
                        'Chamoli',
                        'Champawat',
                        'Dehradun',
                        'Haridwar',
                        'Nainital',
                        'Pauri Garhwal',
                        'Pithoragarh',
                        'Rudraprayag',
                        'Tehri Garhwal',
                        'Udham Singh Nagar',
                        'Uttarkashi'
                    ],
                    'West Bengal': [
                        'Alipurduar',
                        'Bankura',
                        'Birbhum',
                        'Cooch Behar',
                        'Dakshin Dinajpur',
                        'Darjeeling',
                        'Hooghly',
                        'Howrah',
                        'Jalpaiguri',
                        'Jhargram',
                        'Kalimpong',
                        'Kolkata',
                        'Malda',
                        'Murshidabad',
                        'Nadia',
                        'North 24 Parganas',
                        'Paschim Bardhaman',
                        'Paschim Medinipur',
                        'Purba Bardhaman',
                        'Purba Medinipur',
                        'Purulia',
                        'South 24 Parganas',
                        'Uttar Dinajpur'
                    ],
                    # Union Territories
                    'Andaman and Nicobar Islands': [
                        'Nicobar',
                        'North and Middle Andaman',
                        'South Andaman'
                    ],
                    'Chandigarh': [
                        'Chandigarh'
                    ],
                    'Dadra and Nagar Haveli and Daman and Diu': [
                        'Dadra and Nagar Haveli',
                        'Daman',
                        'Diu'
                    ],
                    'Delhi': [
                        'Central Delhi',
                        'East Delhi',
                        'New Delhi',
                        'North Delhi',
                        'North East Delhi',
                        'North West Delhi',
                        'Shahdara',
                        'South Delhi',
                        'South East Delhi',
                        'South West Delhi',
                        'West Delhi'
                    ],
                    'Jammu and Kashmir': [
                        'Anantnag',
                        'Bandipora',
                        'Baramulla',
                        'Budgam',
                        'Doda',
                        'Ganderbal',
                        'Jammu',
                        'Kathua',
                        'Kishtwar',
                        'Kulgam',
                        'Kupwara',
                        'Poonch',
                        'Pulwama',
                        'Rajouri',
                        'Ramban',
                        'Reasi',
                        'Samba',
                        'Shopian',
                        'Srinagar',
                        'Udhampur'
                    ],
                    'Ladakh': [
                        'Kargil',
                        'Leh'
                    ],
                    'Lakshadweep': [
                        'Lakshadweep'
                    ],
                    'Puducherry': [
                        'Karaikal',
                        'Mahe',
                        'Puducherry',
                        'Yanam']
                }
            },
            'UAE': {
                'code': 'AE',
                'timezone_offset': 'Asia/Dubai',
                'is_whitelisted': True,
                'states': {
                    'Dubai': [
                        'Deira',
                        'Bur Dubai',
                        'Downtown',
                        'Jumeirah',
                        'Dubai Marina',
                        'Palm Jumeirah'
                    ],
                    'Abu Dhabi': [
                        'Abu Dhabi City',
                        'Al Ain',
                        'Al Dhafra',
                        'Al Reem',
                        'Yas Island',
                        'Saadiyat'
                    ],
                    'Sharjah': [
                        'Sharjah City',
                        'Khor Fakkan',
                        'Kalba',
                        'Dibba Al-Hisn'
                    ],
                    'Ajman': [
                        'Ajman City',
                        'Masfout',
                        'Al Manama'
                    ],
                    'Fujairah': [
                        'Fujairah City',
                        'Dibba Al-Fujairah'
                    ],
                    'Ras Al Khaimah': [
                        'Ras Al Khaimah City',
                        'Al Jazirah Al Hamra',
                        'Rams'
                    ],
                    'Umm Al Quwain': [
                        'Umm Al Quwain City',
                        'Falaj Al Mualla']
                }
            },
            'Saudi Arabia': {
                'code': 'SA',
                'timezone_offset': 'Asia/Riyadh',
                'is_whitelisted': True,
                'states': {
                    'Riyadh Region': [
                        'Riyadh City',
                        'Al Kharj',
                        'Ad Diriyah',
                        'Dawadmi',
                        'Wadi ad-Dawasir',
                        'Majmaah'
                    ],
                    'Makkah Region': [
                        'Makkah City',
                        'Jeddah',
                        'Taif',
                        'Rabigh',
                        'Al Qunfudhah',
                        'Khulais'
                    ],
                    'Madinah Region': [
                        'Madinah City',
                        'Yanbu',
                        'Al Ula',
                        'Badr',
                        'Khaybar'
                    ],
                    'Eastern Province': [
                        'Dammam',
                        'Al Ahsa',
                        'Al Khobar',
                        'Dhahran',
                        'Al Jubail',
                        'Hafr Al Batin',
                        'Qatif',
                        'Khafji'
                    ],
                    'Asir Region': [
                        'Abha',
                        'Khamis Mushait',
                        'Bisha',
                        'Mahayil',
                        'Al Namas'
                    ],
                    'Tabuk Region': [
                        'Tabuk City',
                        'Neom',
                        'Umluj',
                        'Al Wajh',
                        'Duba'
                    ],
                    'Hail Region': [
                        'Hail City',
                        'Baqaa',
                        'Al Ghazalah'
                    ],
                    'Al Qassim Region': [
                        'Buraidah',
                        'Unaizah',
                        'Ar Rass',
                        'Al Bukayriyah'
                    ],
                    'Jizan Region': [
                        'Jizan City',
                        'Sabya',
                        'Abu Arish',
                        'Samtah',
                        'Farasan'
                    ],
                    'Najran Region': [
                        'Najran City',
                        'Sharurah',
                        'Hubuna'
                    ],
                    'Al Baha Region': [
                        'Al Baha City',
                        'Baljurashi',
                        'Al Mikhwah'
                    ],
                    'Northern Borders Region': [
                        'Arar',
                        'Rafha',
                        'Turaif'
                    ],
                    'Al Jawf Region': [
                        'Sakaka',
                        'Dumat Al Jandal',
                        'Qurayyat']
                }
            }
        }

        self.stdout.write(self.style.WARNING('Starting geographic data population...'))

        for country_name, country_info in geo_data.items():
            # 1. Update or create the Country
            country, created = MasterCountry.objects.update_or_create(
                name=country_name,
                defaults={
                    'code': country_info['code'],
                    'timezone_offset': country_info['timezone_offset'],
                    'is_whitelisted': country_info['is_whitelisted']
                }
            )
            
            status = "Created" if created else "Updated/Found"
            self.stdout.write(self.style.SUCCESS(f'{status} Country: {country.name}'))

            # 2. Create the States/Regions
            for state_name, districts in country_info['states'].items():
                state, state_created = MasterState.objects.get_or_create(
                    name=state_name,
                    country=country
                )
                
                # 3. Create the Districts/Governorates
                for district_name in districts:
                    district, dist_created = MasterDistrict.objects.get_or_create(
                        name=district_name,
                        state=state
                    )

        self.stdout.write(self.style.SUCCESS('\nSuccessfully populated all geographic data!'))