version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bloodonate_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespassword}
      POSTGRES_DB: ${POSTGRES_DB:-bloodonate}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bloodonate_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloodonate_backend
    restart: always
    command: >
      sh -c "python manage.py migrate && 
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ./backend/media:/app/media
    env_file: 
      - ./backend/.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgrespassword}@db:5432/${POSTGRES_DB:-bloodonate}
    depends_on:
      - db
    networks:
      - bloodonate_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bloodonate_frontend
    restart: always
    networks:
      - bloodonate_net

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80'    # HTTP Traffic
      - '443:443'  # HTTPS Traffic
      - '81:81'    # Admin Dashboard
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - bloodonate_net

networks:
  bloodonate_net:
    driver: bridge

volumes:
  postgres_data: